
    import './styles.scoped.css';
    export default {
  "root": "awsui_root_1tu1f_cjxm9_94",
  "wizard": "awsui_wizard_1tu1f_cjxm9_107",
  "refresh": "awsui_refresh_1tu1f_cjxm9_107",
  "small-container": "awsui_small-container_1tu1f_cjxm9_114",
  "navigation": "awsui_navigation_1tu1f_cjxm9_123",
  "number": "awsui_number_1tu1f_cjxm9_185",
  "circle": "awsui_circle_1tu1f_cjxm9_201",
  "title": "awsui_title_1tu1f_cjxm9_209",
  "active": "awsui_active_1tu1f_cjxm9_238",
  "disabled": "awsui_disabled_1tu1f_cjxm9_249",
  "enabled": "awsui_enabled_1tu1f_cjxm9_259",
  "form": "awsui_form_1tu1f_cjxm9_301",
  "form-header": "awsui_form-header_1tu1f_cjxm9_307",
  "background": "awsui_background_1tu1f_cjxm9_318",
  "form-header-content": "awsui_form-header-content_1tu1f_cjxm9_330",
  "form-component": "awsui_form-component_1tu1f_cjxm9_334",
  "hidden": "awsui_hidden_1tu1f_cjxm9_348",
  "collapsed-steps": "awsui_collapsed-steps_1tu1f_cjxm9_352",
  "collapsed-steps-hidden": "awsui_collapsed-steps-hidden_1tu1f_cjxm9_357",
  "form-header-component-wrapper": "awsui_form-header-component-wrapper_1tu1f_cjxm9_361",
  "form-header-component": "awsui_form-header-component_1tu1f_cjxm9_361",
  "navigation-link": "awsui_navigation-link_1tu1f_cjxm9_374",
  "navigation-link-item": "awsui_navigation-link-item_1tu1f_cjxm9_375",
  "navigation-link-label": "awsui_navigation-link-label_1tu1f_cjxm9_376",
  "navigation-link-active": "awsui_navigation-link-active_1tu1f_cjxm9_380",
  "navigation-link-disabled": "awsui_navigation-link-disabled_1tu1f_cjxm9_385",
  "cancel-button": "awsui_cancel-button_1tu1f_cjxm9_389",
  "previous-button": "awsui_previous-button_1tu1f_cjxm9_390",
  "primary-button": "awsui_primary-button_1tu1f_cjxm9_391",
  "skip-to-button": "awsui_skip-to-button_1tu1f_cjxm9_392",
  "action-buttons": "awsui_action-buttons_1tu1f_cjxm9_396"
};
  