
    import './styles.scoped.css';
    export default {
  "root": "awsui_root_12kfy_1modv_97",
  "tools": "awsui_tools_12kfy_1modv_108",
  "tools-filtering": "awsui_tools-filtering_12kfy_1modv_114",
  "tools-align-right": "awsui_tools-align-right_12kfy_1modv_128",
  "tools-pagination": "awsui_tools-pagination_12kfy_1modv_132",
  "tools-preferences": "awsui_tools-preferences_12kfy_1modv_132",
  "tools-small": "awsui_tools-small_12kfy_1modv_138",
  "table": "awsui_table_12kfy_1modv_144",
  "table-layout-fixed": "awsui_table-layout-fixed_12kfy_1modv_150",
  "wrapper": "awsui_wrapper_12kfy_1modv_154",
  "variant-stacked": "awsui_variant-stacked_12kfy_1modv_163",
  "variant-container": "awsui_variant-container_12kfy_1modv_163",
  "variant-embedded": "awsui_variant-embedded_12kfy_1modv_167",
  "variant-borderless": "awsui_variant-borderless_12kfy_1modv_167",
  "has-header": "awsui_has-header_12kfy_1modv_170",
  "has-footer": "awsui_has-footer_12kfy_1modv_173",
  "cell-merged": "awsui_cell-merged_12kfy_1modv_190",
  "cell-merged-content": "awsui_cell-merged-content_12kfy_1modv_201",
  "empty": "awsui_empty_12kfy_1modv_216",
  "loading": "awsui_loading_12kfy_1modv_220",
  "selection-control": "awsui_selection-control_12kfy_1modv_229",
  "selection-control-header": "awsui_selection-control-header_12kfy_1modv_236",
  "sticky-scrollbar": "awsui_sticky-scrollbar_12kfy_1modv_241",
  "sticky-scrollbar-content": "awsui_sticky-scrollbar-content_12kfy_1modv_250",
  "sticky-scrollbar-visible": "awsui_sticky-scrollbar-visible_12kfy_1modv_253",
  "sticky-scrollbar-native-invisible": "awsui_sticky-scrollbar-native-invisible_12kfy_1modv_256",
  "dark-header": "awsui_dark-header_12kfy_1modv_264",
  "header-secondary": "awsui_header-secondary_12kfy_1modv_269",
  "table-has-header": "awsui_table-has-header_12kfy_1modv_285",
  "header-controls": "awsui_header-controls_12kfy_1modv_289",
  "variant-full-page": "awsui_variant-full-page_12kfy_1modv_293",
  "footer-wrapper": "awsui_footer-wrapper_12kfy_1modv_306",
  "footer": "awsui_footer_12kfy_1modv_306",
  "thead-active": "awsui_thead-active_12kfy_1modv_315",
  "row": "awsui_row_12kfy_1modv_316",
  "row-selected": "awsui_row-selected_12kfy_1modv_317"
};
  