
    import './styles.scoped.css';
    export default {
  "code-editor": "awsui_code-editor_1dgkj_1nu8d_98",
  "code-editor-refresh": "awsui_code-editor-refresh_1dgkj_1nu8d_598",
  "pane": "awsui_pane_1dgkj_1nu8d_610",
  "pane__close-container": "awsui_pane__close-container_1dgkj_1nu8d_621",
  "pane__list": "awsui_pane__list_1dgkj_1nu8d_626",
  "pane__table": "awsui_pane__table_1dgkj_1nu8d_633",
  "pane__item": "awsui_pane__item_1dgkj_1nu8d_638",
  "pane__cell": "awsui_pane__cell_1dgkj_1nu8d_638",
  "pane__item--highlighted": "awsui_pane__item--highlighted_1dgkj_1nu8d_652",
  "pane__location": "awsui_pane__location_1dgkj_1nu8d_673",
  "pane__description": "awsui_pane__description_1dgkj_1nu8d_673",
  "focus-lock": "awsui_focus-lock_1dgkj_1nu8d_688",
  "editor": "awsui_editor_1dgkj_1nu8d_713",
  "editor-refresh": "awsui_editor-refresh_1dgkj_1nu8d_741",
  "status-bar": "awsui_status-bar_1dgkj_1nu8d_746",
  "status-bar-with-hidden-pane": "awsui_status-bar-with-hidden-pane_1dgkj_1nu8d_755",
  "status-bar__left": "awsui_status-bar__left_1dgkj_1nu8d_759",
  "status-bar__left-virtual": "awsui_status-bar__left-virtual_1dgkj_1nu8d_766",
  "status-bar__right": "awsui_status-bar__right_1dgkj_1nu8d_770",
  "status-bar__language-mode": "awsui_status-bar__language-mode_1dgkj_1nu8d_774",
  "status-bar__cursor-position": "awsui_status-bar__cursor-position_1dgkj_1nu8d_774",
  "status-bar__cog-button": "awsui_status-bar__cog-button_1dgkj_1nu8d_779",
  "status-bar-virtual": "awsui_status-bar-virtual_1dgkj_1nu8d_783",
  "tab-button": "awsui_tab-button_1dgkj_1nu8d_789",
  "tab-button--refresh": "awsui_tab-button--refresh_1dgkj_1nu8d_802",
  "tab-button--active": "awsui_tab-button--active_1dgkj_1nu8d_816",
  "tab-button--disabled": "awsui_tab-button--disabled_1dgkj_1nu8d_836",
  "tab-button--divider": "awsui_tab-button--divider_1dgkj_1nu8d_866",
  "tab-button--errors": "awsui_tab-button--errors_1dgkj_1nu8d_873",
  "tab-button--warnings": "awsui_tab-button--warnings_1dgkj_1nu8d_873",
  "loading-screen": "awsui_loading-screen_1dgkj_1nu8d_877",
  "error-screen": "awsui_error-screen_1dgkj_1nu8d_878"
};
  